<?php
// +----------------------------------------------------------------------
// | ETshop [ Rapid development framework for Cross border Mall ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2016 http://www.runtuer.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: theseaer <theseaer@qq.com>
// +----------------------------------------------------------------------
// | Spaticker.php  Version 2017/3/29 体验券
// +----------------------------------------------------------------------
namespace app\promotion\controller\admin;

use app\admin\controller\Admin;
use app\promotion\model\Spaticker as SpatickerModel;

class Spaticker extends Admin
{
    /**
     * @Mark:继承
     * @Author: theseaer <theseaer@qq.com>
     * @Version 2017/3/30
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('coupons_list', null);
        $this->assign('money_unit', null);
    }
    
    /**
     * @Mark:首页列表
     * @return mixed
     * @Author: theseaer <theseaer@qq.com>
     * @Version 2017/3/30
     */
    public function index()
    {
        $name               = input('name');
        if($name){
            $map['title'] 			= array('like', '%'.(string)$name.'%');
            $map['seo_title'] 		= array('like', '%'.(string)$name.'%');
            $map['seo_keywords'] 	= array('like', '%'.(string)$name.'%');
            $map['seo_description'] = array('like', '%'.(string)$name.'%');
        }
        $map['status'] = ['neq', null, 'or'];
        
        $list = SpatickerModel::all(function($query) use ($map){
            $query->where($map)->order('end_time', 'desc');
        });
    
        $this->assign('list', $list);
        $this->assign('meta_title', lang('Spaticker'));
        $this->assign('isused', input('?isused') ? input('isused') : 0);
        $this->assign('_total', SpatickerModel::count());
        return $this->fetch();
    }
}