<?php
// +----------------------------------------------------------------------
// | ETshop [ Rapid development framework for Cross border Mall ]
// +----------------------------------------------------------------------
// 版权所有 @ 深圳市润土信息技术有限公司 禁止任何企业和个人对程序代码以任何形式任何目的再发布。
// +----------------------------------------------------------------------
// | Copyright (c) 2015~2017 http://www.runtuer.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: theseaer <theseaer@qq.com>
// +----------------------------------------------------------------------
// | 预存款充值记录  Version 1.0  2016/3/13
// +----------------------------------------------------------------------
namespace app\order\controller\admin;

use think\Db;
use app\admin\controller\Admin;
use app\order\model\Recharge;
use app\order\service\Recharge as Rechargeapi;

class Predeposit extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //订单状态
        $option = [
            '0'=>lang('Allorders'),
            '1'=>lang('Applying'),
            '2'=>lang('Recharging'),
            '3'=>lang('Recharge Finish'),
            '4'=>lang('Invilid'),
        ];
        $this->assign('option',$option);
    }

    /**
     * @Mark:预存款充值记录
     * @param status int 订单状态
     * @param name string 昵称、订单号、账户查询
     * @param start_time string 开始时间
     * @param end_time string 结束时间
     * @Author yang <502204678@qq.com>
     * @Version 2017/5/18
     * @return mixed
     */
    public function index()
    {
        $index_map  = [];
        //查询条件
        $param      = $this->request->param();
        $status     = isset($param['status']) ? trim($param['status']) : ''; //状态
        $name       = isset($param['name']) ? trim($param['name']) : '';     //关键字
        $start_time = isset($param['start_time']) ? trim($param['start_time']) : ''; //开始时间
        $end_time   = isset($param['end_time']) ? trim($param['end_time']) : '';     //结束时间
    
        $name       ? $index_map['rec_sn|rec_account'] = ['like','%'.$name.'%'] : '';
        //按时间查询
        $start_time ? $index_map['create_time'] = ['>=', strtotime($start_time)] : '';
        $end_time   ? $index_map['create_time'] = ['<=', strtotime($end_time)] : '';
        $status     ? $index_map['status'] = $status : $index_map['status'] = ['>' , '0'];
    
        //同时具备时
        if($start_time && $end_time)
        {
            $index_map['create_time'] = ['between' => [$start_time, $end_time]];
        }
        
        //赋值
        $lists = Rechargeapi::getlist('Recharge', $index_map, 'order_id desc');
        $this->assign('list', $lists['list']);
        $this->assign('page', $lists['page']);
        $this->assign('_total', $lists['total']);
        $this->assign('status', $status);
        $this->assign ("meta_title", lang('Predepositpay'));
        return $this->fetch();
    }


    /**
     * @Mark:预存款充值详情
     * @param ordersn string 订单号
     * @Author yang <502204678@qq.com>
     * @Version 2017/5/18
     * @return mixed
     */
    public function view(){
        $rec_sn = trim(input('ordersn'));
        $data = Recharge::recDetail($rec_sn);
        $this->assign('detail',$data);
        return $this->fetch();
    }

    /**
     * @Mark:删除预存款充值订单
     * @Author yang <502204678@qq.com>
     * @Version 2017/5/18
     * @return mixed
     */
    public function delete(){
        $ids = input('param.');
        if (empty($ids['ids'])) return json(['code'=>0,'msg'=>lang('Error_Param')]);
        $re = Db::name('recharge')->where('order_id','in',$ids['ids'])->update(['delete_time'=>time()]);
        if ($re !== false) {
            $this->success(lang('Deleteok'));
        } else {
            $this->error(lang('Deleteerror'));
        }
    }

    /**
     * @Mark:导出excel
     * @return mixed
     * @Author: yang <theseaer@qq.com>
     * @Version 2017/5/18
     */
    public function export()
    {
        $ids = input('param.');
        $title = array(
            lang('Order_sn'),
            lang('Nickname'),
            lang('Referer'),
            lang('Money'),
            lang('Recharge Account'),
            lang('Payment_type'),
            lang('Status'),
            lang('Trade_no'),
            lang('Operate_time'),
            lang('IP Address')
        );
        $where = array('order_id'=>['in',$ids['ids']]);
        $field = ['rec_sn','uid','referer','rec_money','rec_account','pay_name','status','trade_no','create_time','finish_time','rec_ip'];
        $data = Db::name('recharge')
            ->where($where)
            ->field($field)
            ->select();
        $a = exportexcel($data,$title,time_format(time()));
        return ['code'=>1,'msg'=>'OK'];
    }

}