<?php
// +----------------------------------------------------------------------
// | ETshop [ Rapid development framework for Cross border Mall ]
// +----------------------------------------------------------------------
// 版权所有 @ 深圳市润土信息技术有限公司 禁止任何企业和个人对程序代码以任何形式任何目的再发布。
// +----------------------------------------------------------------------
// | Copyright (c) 2015~2017 http://www.runtuer.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: theseaer <theseaer@qq.com>
// +----------------------------------------------------------------------
// | 店铺模板  Version 1.0  2016/3/13
// +----------------------------------------------------------------------
namespace app\seller\controller\admin;

use app\admin\controller\Admin;
use think\Request;
use app\seller\service\Template as TemplateApi;

class Shoptpl extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->conDb = 'Template';
    }
    
    /**
     * @Mark:模板列表
     * @return mixed
     * @Author: theseaer <theseaer@qq.com>
     * @Version 2017/6/12
     */
    public function index()
    {
        $data = TemplateApi::getlist($this->conDb);
        $this->assign('list', $data['list']);
        $this->assign("meta_title", lang('Shopstpl'));
        return $this->fetch();
    }
    
    public function savedata()
    {
        $data = $this->request->post();
        if (!isset($data['status'])) $this->request->post(['status' => 0]);
        parent::savedata();
    }
    
    /**
     * @Mark:结算详情
     * @return mixed
     * @Author: theseaer <theseaer@qq.com>
     * @Version 2016/12/15
     */
    public function detail()
    {
        $this->assign("meta_title", lang('sDetail'));
        return $this->fetch();
    }
}