<?php
// +----------------------------------------------------------------------
// | ETshop [ Rapid development framework for Cross border Mall ]
// +----------------------------------------------------------------------
// 版权所有 @ 深圳市润土信息技术有限公司 禁止任何企业和个人对程序代码以任何形式任何目的再发布。
// +----------------------------------------------------------------------
// | Copyright (c) 2015~2017 http://www.runtuer.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: yang <502204678@qq.com>
// +----------------------------------------------------------------------
// | Appeal 申诉 Version 1.0  2017/5/23
// +----------------------------------------------------------------------
namespace app\member\controller\admin;

use app\admin\controller\Admin;
use app\member\service\Appeal as AppealApi;

class Appeal extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->conDb = 'Appeal';
    }
    
    /**
     * @Mark:覆盖父类方法，申诉列表
     * @param
     * @Author yang <502204678@qq.com>
     * @Version 2017/5/22
     * @return mixed
     */
    public function index()
    {
        $where   = [];
        $params  = $this->request->param();
        isset($params['start_time']) ? $where['create_time'][] = ['>=', strtotime(trim($params['start_time']))] : '';
        isset($params['end_time']) ? $where['create_time'][] = ['<=', strtotime(trim($params['end_time']))] : '';
        
        isset($params['name']) ? $where['user_name|operator|user_id|operator_id|reason'][] = ['like', '%' . trim(input('name')) . '%'] : '';
        
        $data = AppealApi::getlist($this->conDb, $where);
        $this->assign('list', $data['list']);
        return $this->fetch();
    }
    
    /**
     * @Mark:申诉审核     覆盖父类方法
     * @Author yang <502204678@qq.com>
     * @Version 2017/5/22
     * @return mixed
     */
    function savedata()
    {
        $data = input('param.');
        //测试数据   yang  2017/5/24   start
        $data['operator'] = 'yang';
        $data['operator_id'] = 1;
        //测试数据   yang  2017/5/24   end
        $re = \app\member\service\Appeal::checkAppeal($data);
        if ($re === true) {
            $this->success(lang('Reply Success'),'index');
        } else {
            return $re;
        }
    }
    
}