<?php 

$query = $this->db->query("
	DROP TABLE IF EXISTS `".DB_PREFIX ."mega_menu`
");

$query = $this->db->query("
	CREATE TABLE IF NOT EXISTS `".DB_PREFIX."mega_menu` (
		`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
		`parent_id` int(11) NOT NULL,
		`rang` int(11) NOT NULL,
		`icon` varchar(255) NOT NULL DEFAULT '',
		`name` text,
		`link` text,
		`description` text,
		`new_window` int(11) NOT NULL DEFAULT '0',
		`status` int(11) NOT NULL DEFAULT '0',
		`position` int(11) NOT NULL DEFAULT '0',
		`submenu_width` text,
		`submenu_type` int(11) NOT NULL DEFAULT '0',
		`content_width` int(11) NOT NULL DEFAULT '12',
		`content_type` int(11) NOT NULL DEFAULT '0',
		`content` text,
		PRIMARY KEY (`id`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1
");

$query = $this->db->query("
		INSERT INTO `".DB_PREFIX."mega_menu` (`id`, `parent_id`, `rang`, `icon`, `name`, `link`, `description`, `new_window`, `status`, `position`, `submenu_width`, `submenu_type`, `content_width`, `content_type`, `content`) VALUES
		(1, 0, 0, '', 'a:1:{i:1;s:7:\"Fashion\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(3, 1, 1, '', 'a:1:{i:1;s:10:\"S1 Fashion\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:872:\"&lt;p&gt;&lt;a onclick=&quot;index.php?route=product/special&quot; href=&quot;index.php?route=product/special&quot; style=&quot;color:#e70c0c;font-weight: 700;&quot;&gt;Sale&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;font-weight: 700;&quot;&gt;New&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;font-weight: 700;&quot;&gt;New Collection&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;font-weight: 700;&quot;&gt;Casual&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;font-weight: 700;&quot;&gt;Suits&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;font-weight: 700;&quot;&gt;Blacksmith&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;font-weight: 700;&quot;&gt;Sport&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(4, 1, 2, '', 'a:1:{i:1;s:10:\"S2 Fashion\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:1049:\"&lt;p style=&quot;color:#313131;font-weight: 700;font-size:12px;&quot;&gt;Clothing&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Coats&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Outerwear&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Blazers&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Leather&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Cardigans and sweaters&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shirt&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;T-shirts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Polo shirts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Pants&lt;/a&gt; &lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Jeans&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shorts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Pyjamas&lt;/a&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(5, 1, 3, '', 'a:1:{i:1;s:10:\"S3 Fashion\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:902:\"&lt;p style=&quot;font-size: 12px;color:#313131;font-weight: 700;&quot;&gt;Accessories&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shoes&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bags&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Belts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Leather goods&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bracelets&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Gloves&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Ties&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Sunglasses&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Hats and caps&lt;/a&gt; &lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Other accessories&lt;/a&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(6, 1, 4, '', 'a:1:{i:1;s:10:\"S4 Fashion\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:728:\"&lt;p style=&quot;font-size: 12px;color:#313131;font-weight: 700;&quot;&gt;Catalogue&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Winter 2015&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2015 Autumn&lt;/a&gt;&lt;br&gt;&lt;/p&gt;&lt;p style=&quot;font-size: 12px;color:#313131;font-weight: 700;&quot;&gt;Lookbooks&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2014 December&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2014 November&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2014 August&lt;/a&gt;&lt;br&gt;&lt;/p&gt;&lt;p style=&quot;font-size: 12px;color:#313131;font-weight: 700;&quot;&gt;The Post&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(7, 1, 5, '', 'a:1:{i:1;s:10:\"S5 Fashion\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:199:\"&lt;a onclick=&quot;index.php?route=product/special&quot; href=&quot;index.php?route=product/special&quot;&gt;&lt;img src=&quot;http://oc.themeglobal.com/images/superstar/sale.jpg&quot;&gt;&lt;/a&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(8, 0, 6, '', 'a:1:{i:1;s:21:\"Sports &amp; Outdoors\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(15, 8, 7, '', 'a:1:{i:1;s:22:\"S7 Sport &amp; Outdoor\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:653:\"&lt;a href=&quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot;&gt;Featured&lt;/a&gt;&lt;p&gt;&lt;a href=&quot;#&quot;&gt;Launch Calendar&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;NikeLab&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Best Sellers&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Sneaker Hook Ups&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Nike Pro Combat&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Nike Lunar&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Gear Up For Sport&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;New Releases&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Clearance&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(16, 8, 8, '', 'a:1:{i:1;s:22:\"S8 Sport &amp; Outdoor\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:1370:\"&lt;a href=&quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot;&gt;Shoes&lt;/a&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Running&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Basketball&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Training&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Football&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Soccer&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Baseball&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Skateboarding&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Golf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Tennis&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Nike Sportswear&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Special Field Boots&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=61&quot;&gt;Customize with NIKEiD&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(17, 8, 9, '', 'a:1:{i:1;s:22:\"S9 Sport &amp; Outdoor\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:753:\"&lt;a href=&quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot;&gt;Clothing&lt;/a&gt;&lt;p&gt;&lt;a href=&quot;#&quot;&gt;Shirts&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;T-Shirts&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Tank Tops&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Jerseys&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Hoodies &amp;amp; Sweatshirts&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Jackets &amp;amp; Vests&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Shorts&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Tights&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Pants&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Base Layer&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Swimwear&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(18, 8, 10, '', 'a:1:{i:1;s:23:\"S10 Sport &amp; Outdoor\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:600:\"&lt;a href=&quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot;&gt;Gear&lt;/a&gt;&lt;p&gt;&lt;a href=&quot;#&quot;&gt;Nike+ FuelBand SE&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Socks&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Hats &amp;amp; Caps&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Bags &amp;amp; Backpacks&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Golf Clubs&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Balls&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Nike+ Gear&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Gloves &amp;amp; Mitts&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(19, 8, 11, '', 'a:1:{i:1;s:23:\"S11 Sport &amp; Outdoor\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:485:\"&lt;a href=&quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot;&gt;Fan Gear&lt;/a&gt;&lt;p&gt;&lt;a href=&quot;#&quot;&gt;NFL&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Collegiate&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;MLB&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;National Soccer&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Club Soccer&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;FC Barcelona Store&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(20, 8, 12, '', 'a:1:{i:1;s:23:\"S12 Sport &amp; Outdoor\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:488:\"&lt;div style=&quot;text-align: center;&quot;&gt;&lt;a href=&quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot;&gt;Hot Product&lt;/a&gt;&lt;p style=&quot;font-size: 18px; font-weight: 600;color:#333333;&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://oc.themeglobal.com/images/superstar/m6_small2.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot;&gt;Nike Pro Supernatural&lt;/a&gt;&lt;/p&gt;&lt;p&gt;$29&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(22, 0, 19, '', 'a:1:{i:1;s:11:\"Accessories\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(23, 0, 20, '', 'a:1:{i:1;s:18:\"Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '800px', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(24, 23, 21, '', 'a:1:{i:1;s:21:\"S1 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:529:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot; #&quot;=&quot;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu1.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot; #&quot;=&quot;&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;Televisions &amp;amp; Video&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(25, 23, 22, '', 'a:1:{i:1;s:21:\"S2 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:535:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot; #&quot;=&quot;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu2.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot; #&quot;=&quot;&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;Home Audio &amp;amp; Home Theater&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(26, 23, 23, '', 'a:1:{i:1;s:21:\"S3 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:489:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu3.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;Digital Cameras&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(27, 23, 24, '', 'a:1:{i:1;s:21:\"S4 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:515:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot; #&quot;=&quot;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu4.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot; #&quot;=&quot;&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;Video Cameras&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(28, 23, 25, '', 'a:1:{i:1;s:21:\"S5 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:488:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu5.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;Portable Audio&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(29, 23, 26, '', 'a:1:{i:1;s:21:\"S6 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:501:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu6.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;Mobile Phones &amp; Tablets&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(30, 23, 27, '', 'a:1:{i:1;s:21:\"S7 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:485:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu7.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;PlayStation&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(31, 23, 28, '', 'a:1:{i:1;s:21:\"S8 Photo &amp; Camera\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:492:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/megamenu8.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot; style=&quot;font-size: 12px; font-weight: 700;&quot; target=&quot;_self&quot;&gt;Business Solutions&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(32, 0, 29, '', 'a:1:{i:1;s:4:\"Sale\";}', 'index.php?route=product/special', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(33, 0, 30, '', 'a:1:{i:1;s:6:\"Stores\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '900px', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(34, 33, 31, '', 'a:1:{i:1;s:3:\"Map\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:275:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;http://themeglobal.com/opencart/kingstorepro/image/catalog/kingstorepro/location.jpg&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(35, 33, 32, '', 'a:1:{i:1;s:7:\"Store 1\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:290:\"&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;font-size: 12px;font-weight: 700;&quot;&gt;Superstar 1&lt;/a&gt;&lt;/p&gt;&lt;p style=&quot;font-size:12px;&quot;&gt;225-235, Oxford Street LONDON&lt;br&gt;&lt;br&gt;020-7534-3505&lt;br&gt;&lt;br&gt;Monday - Sunday 10:45 am - 10:00 pm&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(36, 33, 33, '', 'a:1:{i:1;s:7:\"Store 2\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:289:\"&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;font-size: 12px;font-weight: 700;&quot;&gt;Superstar 2&lt;/a&gt;&lt;/p&gt;&lt;p style=&quot;font-size:12px;&quot;&gt;106-112, Regent Street LONDON&lt;br&gt;&lt;br&gt;207-434-3866&lt;br&gt;&lt;br&gt;Monday - Sunday 10:45 am - 10:00 pm&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(37, 33, 34, '', 'a:1:{i:1;s:7:\"Store 3\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:282:\"&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;font-size: 12px;font-weight: 700;&quot;&gt;Superstar 3&lt;/a&gt;&lt;/p&gt;&lt;p style=&quot;font-size:12px;&quot;&gt;1 Cour de Rome PARIS&lt;br&gt;&lt;br&gt;01-44-53-73-30&lt;br&gt;&lt;br&gt;Monday - Sunday 10:45 am - 10:00 pm&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(38, 0, 35, '', 'a:1:{i:1;s:11:\"Information\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '220px', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(39, 38, 36, '', 'a:1:{i:1;s:5:\"Links\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:1154:\"&lt;div class=&quot;hover-menu&quot;&gt;&lt;div class=&quot;menu&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;Product Support&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;Mobile Support&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;PlayStation Support&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;Entertainment Support&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;Online Support&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;Drivers &amp; Software&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;Product Repair&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot; onclick=&quot;window.location = &quot;#&quot;;&quot;&gt;Product Registration&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(40, 0, 37, '', 'a:1:{i:1;s:15:\"News &amp; Blog\";}', 'index.php?route=news/ncategory', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}')
		");
?>